package com.lucaswangdev.entity;

/**
* 
* <p>
* ApiMock
* </p>
* <p>
* auto generated by jasmine, please do not modify it!
* </p>
*/
public class ApiMock {

    /**
    * 主键
    * type BIGINT
    */
    private Long id;
    /**
    * mock接口url
    * type VARCHAR
    */
    private String apiPath;
    /**
    * mock接口content
    * type VARCHAR
    */
    private String apiContent;
    /**
    * 延时
    * type INT
    */
    private Integer delay;
  
    /**
    * getter 主键
    */
	public Long getId() {
		return id;
	}

    /**
    * setter 主键
    */
	public void setId(Long id) {
		this.id = id;
	}

    /**
    * getter mock接口url
    */
	public String getApiPath() {
		return apiPath;
	}

    /**
    * setter mock接口url
    */
	public void setApiPath(String apiPath) {
		this.apiPath = apiPath;
	}

    /**
    * getter mock接口content
    */
	public String getApiContent() {
		return apiContent;
	}

    /**
    * setter mock接口content
    */
	public void setApiContent(String apiContent) {
		this.apiContent = apiContent;
	}

    /**
    * getter 延时
    */
	public Integer getDelay() {
		return delay;
	}

    /**
    * setter 延时
    */
	public void setDelay(Integer delay) {
		this.delay = delay;
	}

  
/** The above part of the comment is auto generated, the following part is written by the user, please do not delete this comment. */

}